### ISSUE TITLE
Author page does not have proper twitter card

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/news-theme#18]
<img width="564" alt="twitter_card" src="https://user-images.githubusercontent.com/4591597/59037125-4f0a3480-8879-11e9-9bd6-5dc3dfc6532d.png">

https://twitter.com/Syknapse/status/1136530592395399168

**Comment by sunnyssr** [comment]
Instead of including default header template on author page, we can use the one with proper meta tags? Can it be achieved this way or is there any better way?

**Comment by ahmadabdolsaheb** [comment]
yes that is a good approach @sunnyssr.  we just need to have a name="twitter:image" meta tag. I think we should  repost this issue on ghost's issue tracker since the whole ghost community could benefit from a fix to this issue.

**Comment by sunnyssr** [comment]
Hey,
Any update on this one?

**Comment by ahmadabdolsaheb** [comment]
Hi @sunnyssr,
Updating the cover photo cover  for each author would cause result in the addition of the correct meta tags.

the reason that they have not added a fallback is to ensure good resolution for the twitter card image. 

https://github.com/TryGhost/Ghost/issues/10988#issuecomment-518280508

**Comment by sunnyssr** [comment]
@ahmadabdolsaheb
Can we show the author profile image instead of cover photo?
