### ISSUE TITLE
create a forum thread only when someone comments.

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/news-theme#43]

**Comment by ahmadabdolsaheb** [comment]
related threads:
https://meta.discourse.org/t/embedding-but-dont-automatically-create-a-topic-until-a-user-chooses-to-comment/61450/54

https://meta.discourse.org/t/paid-preference-to-create-embed-a-topic-via-javascript-only-when-a-user-clicks-the-start-discussion-link/78593/6

**Comment by raisedadead** [comment]
See https://github.com/freeCodeCamp/freeCodeCamp/issues/36766
