### ISSUE TITLE
Developer News 404 page search box is unstyled

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/news-theme#53]
<img width="1418" alt="Developer_News___404_-_Page_not_found" src="https://user-images.githubusercontent.com/985197/61886794-fa248b00-aec5-11e9-8506-3291597b4c02.png">

**Comment by ahmadabdolsaheb** [comment]
@sunnyssr,
go ahead and let me know if you need some help.
you need to have ghost installed locally.

**Comment by sunnyssr** [comment]
Yeah sure! I will let you know if I have some problem.
I have got it set up.
Thank you :D
