### ISSUE TITLE
News: Post Category Link 404

### ISSUE THREAD

**Issue by colbyfayock** [freeCodeCamp/news-theme#61]
I can't reproduce this on any other tags that I've found yet, but the CSS in JS tag produces a 404 on the post page category link. https://www.freecodecamp.org/news/you-dont-need-css-in-js-why-i-use-stylesheets/

I double checked that I added the tag as one of the preselected autocomplete options in Ghost, which I did and tried to update. Still same issue.

![image](https://user-images.githubusercontent.com/1045274/63225101-df7ac480-c19a-11e9-831a-a013e4e2284b.png)

**Comment by ahmadabdolsaheb** [comment]
Thanks @colbyfayock, for reporting this issue. this issue has been resolved.
